### PR TITLE
Timeout TCP connect

### PR DESCRIPTION
**Pull request by william-ferguson-au**
When a WebSocket client is connected to a WebSocket is the WiFi AP drops out, the current behaviour of the WebsocketClient is to immediately attempt to reconnect in the #loop method. When it reconnects, it does so using the indefinite timeout tcp#connect method.

This causes either deadlock or a crash when the WiFI station finally re-establishes itself when the WiFi AP comes back up (at least on the ESP32).

The solution is to use #connect with a timeout so that the select is released on the socket handle.

### CODE REVIEW

**Comment by Links2004** [comment]
Hi,

thanks for the PR can you please check you diff, it looks like your editor has reformatted the full file.
and the changes only is compatible with the ESP32 see:
https://travis-ci.org/Links2004/arduinoWebSockets/builds/546262868?utm_source=github_status&utm_medium=notification

you can use:

```cpp
#if defined(ESP32)
 ESP32 only code
#else
 all other platforms
#endif
```

to write code for one specific platform.

**Comment by william-ferguson-au** [comment]
Thanks @Links2004, I didn't realise that the change was ESP32 specific.

I don't seem to be able to modify WebSocketsClient.cpp without GitHub thinking that the entire file has changed (I suspect it is to do with line endings). My editor (CLion) only shows the changed lines as changed (with DoNotIgnoreWhiteSpace), so I suspect it is occuring when Giot is pushing to GitHub.

Not sure why it doesn't occur for the change to WebSockets.cpp though.

This is the change that needs to occur at line 167 of WebSocketsClient.cpp
Would you mind applying it for me?
```
        DEBUG_WEBSOCKETS("[WS-Client][loop] About to connect to WS\n");
#if defined(ESP32)
        // Timeout after 1 second to ensure we don't block indefinitely when WiFi AP goes away.
        if(_client.tcp->connect(_host.c_str(), _port, 1000)) {
#else
        if(_client.tcp->connect(_host.c_str(), _port)) {
#endif
```

**Comment by Links2004** [comment]
the connect timeout will now be set to `WEBSOCKETS_TCP_TIMEOUT` for the ESP32

**Comment by william-ferguson-au** [comment]
Awesome, thanks @Links2004

**Pull request closed without merging**
