### PR TITLE
Remove compiler warnings

### PR DESCRIPTION
**Pull request by hasenradball**
# Remove compiler warnings due to:

## changed `WebSockets.cpp` file
- Compiler complains about wrong printf format specifier when use `millis()`.

Bildschirmfoto vom 2023-11-27 11-42-07

## changed `WebSocketsServer.cpp` file
- update to use `accept`instead to deprecated `available`

Bildschirmfoto vom 2023-11-27 11-47-10

### CODE REVIEW

**Comment by hasenradball** [comment]
@Links2004 
Hi can you maybee explain why all checks fail?
I have no clue and the error meassage does not say anything.

**Comment by Links2004** [comment]
@hasenradball CI/CD has been fixed, an you rebase your branch, to get the test running?

**Comment by hasenradball** [comment]
@Links2004 Hi, sorry I did not get your Question.

Should I rebase my branch and push again?

**Comment by Links2004** [comment]
yes, exactly.

**Comment by hasenradball** [comment]
@Links2004 
look fine now.

**Review by Links2004 — APPROVED** [review]

**Pull request merged**
