### PR TITLE
make masking RFC complaint and fix #208

### LINKED ISSUE #208: Pong response contains a mask
Pong response to my ping requests contains a mask and overall it looks like this "8a 80 00 00 00 00". I'm not entirely sure if sending a mask without data is a valid case.

### PR DESCRIPTION
**Pull request by sanketplus**
wasn't able to test. Hoping for CI to test it. Please let me know if any changes required.

### CODE REVIEW

**Comment by sanketplus** [comment]
build seems to be consistent with with latest commit. As in same first 3 test failures. Otherwise it looks good. Still did not get a chance to test in to device though. The end to end tests.

**Comment by Links2004** [comment]
the changes looking good, looks like Arduino has a build problem with the board.
will take a look this weckend.

**Comment by sanketplus** [comment]
nice, it seems to be passing now. Let me know if any other changes are required from my side @Links2004

**Comment by Links2004** [comment]
all good, have merged the changes

**Pull request merged**
