### PR TITLE
fix WSclient_t initialization in server

### PR DESCRIPTION
**Pull request by d-a-v**
Reference: [discussion](https://github.com/Links2004/arduinoWebSockets/pull/575#issuecomment-720613241) with @mcspr

(opened to discussion or any other solution)

### CODE REVIEW

**Comment by d-a-v** [comment]
If the N `WSclient_t` instances from the array do not need to be ***re***-initialized, then in-place destructor and constructor are not needed. `WSclient_t` members are always initialized to their default values (0 for scalar, respective contructor for other members including the Strings - this initialization was later destroyed by the former `memset()`).
Then a `WSclient_t::init(num, interval/count...)` is sufficient, and would come after the constructors are called (which happens at the time of the array allocation).

**Comment by mcspr** [comment]
> Then a WSclient_t::init(num, interval/count...) is sufficient, and would come after the constructors are called (which happens at the time of the array allocation).

Basically, comes down to this.

Note that `classname() = default;` does not always guarantee that it is called :) e.g.
```cpp
Object obj;
```
vs.
```cpp
Object obj = Object();
```
Which is exactly the issue the default values in the class body always help to avoid (and I really like that option tbh)

Just to repeat myself - explicit dtor + ctor through placement new could be replaced with either copy-assignment or move-assignment, depending on what we want with the resulting objects.
e.g. like to preserve existing buffers of Strings, which what is currently happening after String="", since it just sets length to 0 and leaves the existing buffer.
Might also be less scary to look at.

**Comment by mcspr** [comment]
Small code example re. "And not to mention different ctors, which need to manually call the default one."
https://godbolt.org/z/rrY9jP

**Comment by d-a-v** [comment]
Well OK, thanks!
I just proved myself through an example that scalars are not initialized by default constructor,
*but* member with constructors are (so scalars have no implicit constructors).

**Comment by d-a-v** [comment]
@mcspr Do you agree with the last commit ?

**Comment by mcspr** [comment]
(ref. gitter + 9d9f892)
I think this covers it.

init() alternative is also doing it like https://godbolt.org/z/zaTjvT
ping intervals are dynamic though, but it seems to be handled via enableHeartbeat

**Comment by d-a-v** [comment]
@Links2004 This PR is ready for reviewing, sorry for the noise ;)

**Pull request merged**
